### ISSUE TITLE
Some problem with client.secret

### ISSUE THREAD

**Issue by ronek22** [ryanbaumann/Strava-Stream-to-CSV#1]
Hi, Ryan
I filled client.secret with correct codes, but i get an error.
It's open on the browser:
`{"message":"Bad Request","errors":[{"resource":"Application","field":"client_id","code":"invalid"}]}` 

On the terminal:

```
(firefox:20984): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox:20984): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

(firefox:20984): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox:20984): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

(firefox:20984): IBUS-WARNING **: Unable to connect to ibus: Nie można połączyć: Połączenie odrzucone
```

**Comment by ryanbaumann** [comment]
@ronek22 looks like your client API code wasn't parsed correctly.  Try printing out your Client ID and client secret to the console to verify that there were parsed correctly by the Python script.

Please tag me @ryanbaumann for future requests and I'll be sure to get back to you sooner!

**Comment by ronek22** [comment]
I was writing client id, and client secret like this "<client_id, client_secret>", but it must be look like this: "client_id,client_secret" without angle brackets.
